/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import {
  type WithSearch_codeItemRequestBuilder,
  WithSearch_codeItemRequestBuilderRequestsMetadata,
} from "./item/index.ts";
// @ts-ignore
import {
  type BaseRequestBuilder,
  type KeysToExcludeForNavigationMetadata,
  type NavigationMetadata,
} from "@microsoft/kiota-abstractions";

/**
 * Builds and executes requests for operations under /api/v1/searchcode
 */
export interface SearchcodeRequestBuilder
  extends BaseRequestBuilder<SearchcodeRequestBuilder> {
  /**
   * Gets an item from the JPostDigiAddrSDK.api.v1.searchcode.item collection
   * @param search_code - 郵便番号  (3桁以上の数値。入力された値が7桁未満であった場合、入力値から始まるデータをパターン検索する。)- 事業所個別郵便番号- デジタルアドレス
   * @returns {WithSearch_codeItemRequestBuilder}
   */
  bySearch_code(search_code: string): WithSearch_codeItemRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const SearchcodeRequestBuilderUriTemplate =
  "{+baseurl}/api/v1/searchcode";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const SearchcodeRequestBuilderNavigationMetadata: Record<
  Exclude<keyof SearchcodeRequestBuilder, KeysToExcludeForNavigationMetadata>,
  NavigationMetadata
> = {
  bySearch_code: {
    requestsMetadata: WithSearch_codeItemRequestBuilderRequestsMetadata,
    pathParametersMappings: ["search_code"],
  },
};
/* tslint:enable */
/* eslint-enable */
