/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import {
  type AddresszipRequestBuilder,
  AddresszipRequestBuilderRequestsMetadata,
} from "./addresszip/index.ts";
// @ts-ignore
import {
  type JRequestBuilder,
  JRequestBuilderNavigationMetadata,
} from "./j/index.ts";
// @ts-ignore
import {
  type SearchcodeRequestBuilder,
  SearchcodeRequestBuilderNavigationMetadata,
} from "./searchcode/index.ts";
// @ts-ignore
import {
  type BaseRequestBuilder,
  type KeysToExcludeForNavigationMetadata,
  type NavigationMetadata,
} from "@microsoft/kiota-abstractions";

/**
 * Builds and executes requests for operations under /api/v1
 */
export interface V1RequestBuilder extends BaseRequestBuilder<V1RequestBuilder> {
  /**
   * The addresszip property
   */
  get addresszip(): AddresszipRequestBuilder;
  /**
   * The j property
   */
  get j(): JRequestBuilder;
  /**
   * The searchcode property
   */
  get searchcode(): SearchcodeRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const V1RequestBuilderUriTemplate = "{+baseurl}/api/v1";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const V1RequestBuilderNavigationMetadata: Record<
  Exclude<keyof V1RequestBuilder, KeysToExcludeForNavigationMetadata>,
  NavigationMetadata
> = {
  addresszip: {
    requestsMetadata: AddresszipRequestBuilderRequestsMetadata,
  },
  j: {
    navigationMetadata: JRequestBuilderNavigationMetadata,
  },
  searchcode: {
    navigationMetadata: SearchcodeRequestBuilderNavigationMetadata,
  },
};
/* tslint:enable */
/* eslint-enable */
