/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import {
  type TokenRequestBuilder,
  TokenRequestBuilderRequestsMetadata,
} from "./token/index.ts";
// @ts-ignore
import {
  type BaseRequestBuilder,
  type KeysToExcludeForNavigationMetadata,
  type NavigationMetadata,
} from "@microsoft/kiota-abstractions";

/**
 * Builds and executes requests for operations under /api/v1/j
 */
export interface JRequestBuilder extends BaseRequestBuilder<JRequestBuilder> {
  /**
   * The token property
   */
  get token(): TokenRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const JRequestBuilderUriTemplate = "{+baseurl}/api/v1/j";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const JRequestBuilderNavigationMetadata: Record<
  Exclude<keyof JRequestBuilder, KeysToExcludeForNavigationMetadata>,
  NavigationMetadata
> = {
  token: {
    requestsMetadata: TokenRequestBuilderRequestsMetadata,
  },
};
/* tslint:enable */
/* eslint-enable */
